Project - Jorge Pascual Segovia
IBiDat/dataviz pull request #23
Opened 2023-01-16 14:52 UTC by JorPS

This is my first version of git project

2023-01-16 18:59 UTC, Enchufa2 requested changes
Thanks, now, I've reorganized your files, so first of all **click Pull** in RStudio's git panel to retrieve my commit before making further changes. The main file is now `_projects/2022/100486421/100486421.Rmd`.

Now, the idea is that this should be an article explaining the context, the process, and discussing the charts. See [your classmates' projects](https://csslab.uc3m.es/dataviz/projects.html) for some inspiration.

2023-01-16 18:59 UTC, Enchufa2 commented on _projects/2022/100486421/100486421.Rmd
> +  A short description of the post.
Please add a short description of the post.

2023-01-23 18:00 UTC, JorPS commented
I thought that was the objective of the presentations so the structure is very similar. I already comitted the changes but I don't know if you can see them or if I have to do some process again, Github is kind of a labrynth for me yet.

2023-01-23 18:41 UTC, Enchufa2 commented
Thanks! Merging after some cleanup.

2023-01-23 18:41 UTC, merged

2023-01-23 18:43 UTC, Enchufa2 commented
Published here: https://csslab.uc3m.es/dataviz/projects/2022/100486421/