Edgar test of first part
IBiDat/dataviz pull request #3
Opened 2022-11-13 20:06 UTC by chicurel

2023-01-08 18:19 UTC, Enchufa2 requested changes
Great work! It just requires a few changes. First of all, **click Pull** in RStudio to get a couple of commits I added. Note that I've moved your article back to the 2022 folder, so please edit it there. Please address the comments below, knit the article, commit and push the final changes.

2023-01-08 18:19 UTC, Enchufa2 commented on _projects/2022/100376720/100376720.Rmd
> +![Graph to replicate](original.png){.external width="100%"}
I've downloaded the original to avoid depending on an external resource.

2023-01-08 18:19 UTC, Enchufa2 commented on _projects/2022/100376720/100376720.Rmd
> +df <- read_csv("C:/Users/usuario/Desktop/Master/Data Visualization/Data_on_intergenerational_mobility.csv")
As with the original image, please do the same with the dataset. Move the dataset next to the Rmd, and then read it just by name `read_csv("Data_on_intergenerational_mobility.csv")`.

2023-01-08 18:19 UTC, Enchufa2 commented on _projects/2022/100376720/100376720.Rmd
> +                                     ifelse(Country != "South Korea", paste0(Mobility_perc, "    "), Mobility_perc))), size=3,
There are some lines that are too wide in this chunk. See [the preview](https://deploy-preview-3--mucss-dataviz.netlify.app/_projects/2022/100376720/100376720). Please, make them shorter, typically a maximum of 80 characters.

2023-01-08 18:19 UTC, Enchufa2 commented on _projects/2022/100376720/100376720.Rmd
> +  geom_point(size=3, color = "#b8bdd0", aes(color = Beyond_Sex), data = beyond[beyond$Beyond_Sex != "Beyond_highscool_2014_F",] ) +
There are some lines that are too wide here too. Please make them shorter.

2023-01-09 17:49 UTC, chicurel commented
I added the changes, the only thing is that in the subtitles and titles lines I couldnt mske it smaller because it changes the output. Thank you!

2023-01-09 17:57 UTC, Enchufa2 approved these changes
Thanks, great work!

2023-01-09 17:57 UTC, merged

2023-01-09 18:00 UTC, Enchufa2 commented
Here you are: https://csslab.uc3m.es/dataviz/projects/2022/100376720/