Project - Jieun Park
IBiDat/dataviz pull request #34
Opened 2023-12-11 17:27 UTC by CSSjieun

2024-01-19 00:26 UTC, CSSjieun commented
final version is done, ready for review.

2024-01-19 16:31 UTC, Enchufa2 requested changes
Thanks, I left some comments below. Please address them and let me know when this is ready again.

2024-01-19 16:31 UTC, Enchufa2 commented on _projects/2023/100509696/100509696.Rmd
> +title: "New dataviz project"
Could you please provide a descriptive title?

2024-01-19 16:31 UTC, Enchufa2 commented on _projects/2023/100509696/100509696.Rmd
> +  A short description of the post.
And a descriptive summary about what's the graph about.

2024-01-19 16:31 UTC, Enchufa2 commented on _projects/2023/100509696/100509696.Rmd
> +knitr::include_graphics("~/Desktop/data visualization/ElectricitySourcesLN-superJumbo.webp")
Please copy this file next to this Rmd and commit and push it.

2024-01-19 16:31 UTC, Enchufa2 commented on _projects/2023/100509696/100509696.Rmd
> +data <- read_excel("~/Desktop/data visualization/Net_generation_United_States_all_sectors_annual.xls")
The same for the data. All datasets used here should be put in this directory and pushed as part of the PR.

2024-01-19 16:31 UTC, Enchufa2 commented on _projects/2023/100509696/100509696.Rmd
> +```
Something is missing here?

2024-01-22 10:57 UTC, CSSjieun commented
I changed the things as comment. Could you please check it?

2024-01-22 16:52 UTC, CSSjieun commented
Just in case I added the data in the same directory right next to the Rmd. file and commit and pushed it again.

2024-01-22 18:38 UTC, Enchufa2 approved these changes
Neat! Merging with a few fixes.

2024-01-22 18:38 UTC, merged

2024-01-22 18:43 UTC, Enchufa2 commented
Here's your work, congrats! https://csslab.uc3m.es/dataviz/projects/2023/100509696/