Project - Eric
IBiDat/dataviz pull request #39
Opened 2023-12-15 10:52 UTC by ericinthehaus

The replication of the chart by _FlowingData_ with data from the _American Time Use Survey 2020_.

2023-12-22 19:20 UTC, Enchufa2 requested changes
Nice work! But I would love to see more step-by-step guidance of what you are doing. Think of this as a tutorial for future you. Marking this as a draft PR. Click "ready for review" again when you want me to make another pass.

2023-12-22 19:20 UTC, Enchufa2 commented on _projects/2023/100510783/100510783.Rmd
> +  A short description of the post.
Please add a short abstract of your work here. ;-)

2023-12-22 19:20 UTC, Enchufa2 commented on _projects/2023/100510783/100510783.Rmd
> +library(tidyverse)
Please move this call to the tidyverse to another chunk down below so that the reader knows that you are loading this library.

2023-12-22 19:20 UTC, Enchufa2 commented on _projects/2023/100510783/100510783.Rmd
> +knitr::include_graphics("Screenshot.png")
Apart from the graph itself, it would be nice to have some context. What's the source? Why this graph?

2024-01-19 13:49 UTC, ericinthehaus commented
This article is ready to publish!

2024-01-19 16:17 UTC, Enchufa2 approved these changes
Great job, congrats! Merging with minor fixes.

2024-01-19 16:17 UTC, merged

2024-01-19 16:20 UTC, Enchufa2 commented
And here's your work: https://csslab.uc3m.es/dataviz/projects/2023/100510783/