Inital commit
IBiDat/dataviz pull request #54
Opened 2023-12-20 17:11 UTC by alejandracosta

2023-12-22 11:15 UTC, alejandracosta commented
My project is ready for review! 
Thanks

2023-12-22 19:13 UTC, Enchufa2 requested changes
Nice work! I left you some comments with some fixes and improvements. As always, just modify, re-knit, add, commit and push. Marking this as a draft PR. Click "ready for review" again when you want me to make another pass.

2023-12-22 19:13 UTC, Enchufa2 commented on _projects/2023/100385252/100385252.Rmd
> +cataegories: "2023"
typo

2023-12-22 19:13 UTC, Enchufa2 commented on _projects/2023/100385252/100385252.Rmd
> +## 1. Getting and preparing the data
Please remove the numbering from titles to keep the style of the rest of the projects.

2023-12-22 19:13 UTC, Enchufa2 commented on _projects/2023/100385252/100385252.Rmd
> +```{r echo = FALSE}
Do not use this. The reader must know which libraries you used!

2023-12-22 19:13 UTC, Enchufa2 commented on _projects/2023/100385252/100385252.Rmd
> +showtext::showtext_auto()
Instead of calling this line, it's better to add `fig.showtext=TRUE` to all chunks with graphic output.

2024-01-14 18:57 UTC, Enchufa2 requested changes
A couple more comments. Let me know when this is ready again.

2024-01-14 18:57 UTC, Enchufa2 commented on _projects/2023/100385252/100385252.Rmd
> +
Please show the original plot here. See the example project.

2024-01-14 18:57 UTC, Enchufa2 commented on _projects/2023/100385252/100385252.Rmd
> +data_regions <- read.csv(file = "Geographies.csv", sep = ";") |>
This CSV is missing in the PR.

2024-01-18 19:10 UTC, Enchufa2 commented
Great work, congrats! Merging with a few fixes.

2024-01-18 19:10 UTC, Enchufa2 approved these changes

2024-01-18 19:10 UTC, merged

2024-01-18 19:13 UTC, Enchufa2 commented
And here's your work: https://csslab.uc3m.es/dataviz/projects/2023/100385252/