Project - Daniel
IBiDat/dataviz pull request #55
Opened 2023-12-20 19:45 UTC by daniielperez10

2024-01-18 19:14 UTC, Enchufa2 commented
The project is empty! Please commit and push everything under _projects and let me know when this is ready.

2024-01-18 19:37 UTC, daniielperez10 commented
I think now it should be okay

2024-01-18 19:42 UTC, Enchufa2 commented
Now the YAML header is not compliant with the instructions in the tutorial, and I only see code and no text. Please see your colleagues' projects. Switching back to draft.

2024-01-18 19:51 UTC, daniielperez10 commented
ok, I think I was missing toc : true.
sorry for the inconvenience

2024-01-18 20:01 UTC, Enchufa2 requested changes
Sorry to be blunt, Daniel, but I insist: there is no text in your post. The projects are expected to be blog posts where you guide the reader through your work. You have a bunch of examples in the webpage.

2024-01-18 20:01 UTC, Enchufa2 commented on _projects/2023/1004075443/1004075443.Rmd
> +  A short description of the post.
There is no description, and there is no category.

2024-01-18 20:01 UTC, Enchufa2 commented on _projects/2023/1004075443/1004075443.Rmd
> +date: 2023-12-18
This is not the correct format for the date.

2024-01-18 20:01 UTC, Enchufa2 commented on _projects/2023/1004075443/1004075443.Rmd
> +
There is no text.

2024-01-18 20:01 UTC, Enchufa2 commented on _projects/2023/1004075443/1004075443.Rmd
> +#DATOS PREPARADOS
There are comments in Spanish.

2024-01-19 19:29 UTC, daniielperez10 commented
Dear Iñaki, sorry for the confusion, I still don't know if I am uploading things correctly. I hope everything is correct.

Thank you

2024-01-21 20:43 UTC, Enchufa2 approved these changes
Great work, congrats! I added the dataset and clean things up a bit. Merging.

2024-01-21 20:43 UTC, merged

2024-01-21 20:45 UTC, Enchufa2 commented
And here's your work: https://csslab.uc3m.es/dataviz/projects/2023/1004075443/