Miao Liao-final project 'Working Hours'
IBiDat/dataviz pull request #61
Opened 2024-01-14 22:27 UTC by Miao-Liao

This project consists in the replicaion and alternative representation of graphs from Our World in Data called "Working Hours"

2024-01-15 10:07 UTC, Enchufa2 requested changes
Thanks for your work! Please address the comments below and let me know when this is ready for review again.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +    toc: TRUE
`true`, in lower case.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +preview: original.png
This is to show a image as preview in the gallery, but you didn't add a `original.png` file to the pull request. Please, remove this.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +knitr::opts_chunk$set(echo = FALSE)
Should be `echo=TRUE`. We want the reader to see your code.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +The graph for this project was inspired by a Working Hours article in Our World in Data, which is  about a comparative analysis of average annual hours worked by countries between 1950 and 2019. The
The last link should have the URL to the article between parenthesis.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +working_hours<-read.csv("C:/Users/liaom/Desktop/Courses/数据可视化/pre/123/annual working hours/annual-working-hours-per-worker.csv")
The CSV is missing in the pull request. Please add this file, and then these lines should be just `read.csv("annual-working-hours-per-worker.csv")`.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +data <- read.csv("C:/Users/liaom/Desktop/Courses/数据可视化/pre/123/annual working hours/annual-working-hours-per-worker.csv")
The data was read before, so you can just reuse the `working_hours` variable.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +tm_shape(world_1900) +
The course is about ggplot2, and we have studied how to plot maps with ggplot2. ;-) Please, use ggplot2 for these maps.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +data <- read.csv( "C:/Users/liaom/Desktop/Courses/数据可视化/pre/123/GDP.csv")
This CSV should be added to the pull request too.

2024-01-15 10:07 UTC, Enchufa2 commented on _projects/2024/100508856/100508856.Rmd
> +data <- read.csv("C:/Users/liaom/Desktop/Courses/数据可视化/pre/123/annual-working-hours-vs-gdp-per-capita-pwt/annual-working-hours-vs-gdp-per-capita-pwt.csv")
This is different than before, right? Well... all CSVs should be added to the pull request. ;-)

2024-01-19 19:58 UTC, Miao-Liao commented
Thank you so much ! I've modified the misstakes.

2024-01-22 18:51 UTC, Enchufa2 commented
The CSVs are still missing in the PR. I meant that they should be move inside your project directory, not to C:\. In this way, they will appear in the git panel, and then you can commit and push them here.

2024-01-22 19:15 UTC, Miao-Liao commented
Thank you and I've changed the question about read. csv, I hope it will be OK

2024-01-28 16:40 UTC, Enchufa2 approved these changes
Perfect, thanks! Mergin with some fixes.

2024-01-28 16:41 UTC, merged

2024-01-28 16:44 UTC, Enchufa2 commented
Here's your work: https://csslab.uc3m.es/dataviz/projects/2023/100508856/