Project - <Linghan Zheng>
IBiDat/dataviz pull request #67
Opened 2024-11-04 23:32 UTC by Leeann954

It's my first draft on Github.

2024-12-26 16:57 UTC, Enchufa2 requested changes
Thanks, great work. But the idea is that the file called `_projects/2024/100540803/100540803.Rmd` should be your post, so that it's integrated in the webpage's projects section. So could you please move the contents of `first version.qmd` to the file above and remove this qmd as well as `first-version_files` and `first version_files`? If you need the `images` directory, that should be moved under `_projects/2024/100540803` too.

2025-01-11 16:13 UTC, Leeann954 commented
Hi Inaki,

I have already moved the file to _projects/2024/100540803/100540803.Rmd and deleted the original first version. However, I'm now encountering this conflict message regarding projects.html, projects/projects.json, and sitemap.xml. Could you help me resolve this issue or guide me on the next steps to take?

Thanks!
![image](https://github.com/user-attachments/assets/63aafeec-10b5-48e3-8de3-fb7a009bb50f)

2025-01-11 16:52 UTC, Leeann954 commented
Hi Iñaki,

I have already moved the file to _projects/2024/100540803/100540803.Rmd and deleted the original first version. However, I'm now encountering this conflict message regarding projects.html, projects/projects.json, and sitemap.xml. Could you help me resolve this issue or guide me on the next steps to take?

Thanks!
![image](https://github.com/user-attachments/assets/f2d85409-a7c9-4880-8bf6-f754f313cf2b)

2025-01-13 09:13 UTC, Enchufa2 requested changes
Nice, thanks for the work with ggplot2! Some minor comments below. And don't worry about the conflicts, I'll deal with that.

2025-01-13 09:13 UTC, Enchufa2 commented on _projects/2024/100540803/100540803.Rmd
> +editor: visual
Please, set the header as indicated in the [tutorial](https://csslab.uc3m.es/dataviz/tutorials/project/#adding-your-own-article), where it says "the header should look like this"...

2025-01-13 09:13 UTC, Enchufa2 commented on _projects/2024/100540803/100540803.Rmd
> +![Kobe Plot 1](images/picture1.png){width="100%"} ![Kobe Plot 2](images/picture2.png){width="100%"} ![Kobe Plot3](images/picture3.png){width="100%"} *Note: The original graph can be found on the [Wor
Please set the images as "external" as e.g. David does [here](https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/2024/100535712/100535712.Rmd#L26).

2025-01-13 09:13 UTC, Enchufa2 commented on _projects/2024/100540803/100540803.Rmd
> +data <- read.csv("C://Users/zlh/Downloads/goal14.kobe.csv")
Please add the data here too, and reference it directly instead of using the path in your computer.

2025-01-13 09:13 UTC, Enchufa2 commented on _projects/2024/100540803/100540803.Rmd
> +![Final graph](images/picture4.png){width="100%"}
Instead of adding the static file, just print `p5` above, as you with the previous ones.

2025-01-13 09:13 UTC, Enchufa2 commented on _projects/2024/100540803/100540803.Rmd
> +```{r,message=FALSE, warning=FALSE}
Please add `preview=TRUE`, so that this one is highlighted in the gallery.

2025-01-13 11:33 UTC, Leeann954 commented
Hi Iñaki,
I’ve implemented all the requested changes and addressed the feedback. Please review the updates and let me know if there’s anything else that needs further adjustment. Thank you!

2025-01-13 14:57 UTC, Enchufa2 approved these changes
Thanks, merging!

2025-01-13 14:58 UTC, merged

2025-01-13 15:03 UTC, Enchufa2 commented
Congrats, here you are: https://csslab.uc3m.es/dataviz/projects/2024/100540803/