Project - Pablo Romero
IBiDat/dataviz pull request #68
Opened 2024-11-05 13:51 UTC by pablormd

Initial version of the project.

2024-12-26 17:19 UTC, Enchufa2 requested changes
Nice work! Some comments:

- Please add a caption to the plot and set it as "external" as e.g. David does [here](https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/2024/100535712/100535712.Rmd#L26).
- Please do not hide the chunk where you load the libraries (i.e., do not add `echo=FALSE`). It's important to see which libraries you're using to replicate your code.
- You load many libraries. Are they all necessary? Please remove the ones that are not. (For example, when you load the tidyverse, ggplot2 and others are loaded too).
- Please remove the `rm(list = ls())` line, it's not necessary.
- The text in the charts is too small. I would recommend decreasing the `fig.height` and `fig.width` in the chunk options (keeping the same proportions) to make the text more readable.
- Please add the option `preview=TRUE` to the chunk that produces the chart that you would like to see as preview in the project gallery.
- If you want to highlight sentences in the bullet lists, you can use the `**` markdown syntax (for bold text) instead of the backtricks you are currently using, which are for code.
- The first alternative visualization is tiny too. Apart from tuning the `fig.height` and `fig.width`, you can also try to set the layout option to `l-screen` as I do [here](https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/gapminder/gapminder.Rmd#L291).

2024-12-28 18:27 UTC, pablormd reviewed
Hi Iñaki! I attach the second version with the changes you have proposed and small improvements in text and visualization. With respect to modify the fig.height and fig.width, I have chosen to present all the graphics with l-screen, since I consider that they are visualized much better. Thank you very much!

2025-01-10 10:13 UTC, Enchufa2 approved these changes
Great work! I just set some figures to l-page because l-screen was a bit too much :D, but that's it, merging here!

2025-01-10 10:13 UTC, merged

2025-01-10 10:16 UTC, Enchufa2 commented
And here you are: https://csslab.uc3m.es/dataviz/projects/2024/100529006/