Project - Isabela Zeberio
IBiDat/dataviz pull request #7
Opened 2022-11-18 17:07 UTC by isazeberio

2023-01-04 22:18 UTC, isazeberio commented
Hi Iñaki,
Happy new year!!
I think I'm almost done (I struggled quite a bit with GitHub). Anyways, I had a lot os issues with the size of the plots in R Markdown, and I didn't manage to set plots in a wider span that the margins. I am open to any changes you consider convenient to improve the visualization of the project.
Thank you in advance (sorry for the weird commits)

2023-01-05 12:57 UTC, Enchufa2 commented
Is this ready for review then?

2023-01-05 13:01 UTC, isazeberio commented
Yes, it's ready for review.

2023-01-05 15:27 UTC, Enchufa2 requested changes
Great work! Looks very nice. Just a few comments below. Also, there are some lines of code that are still too wide. It would be nice to wrap them in 80 characters max.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +![Diagram listing the 17 Sustainable Development Goals. Figure from [un.org](https://sdgs.un.org/goals)](/Users/isabelazeberio/Documents/GitHub/dataviz/_projects/2022/100386498/sustainabledevgoals.pn
All these paths should be relative to the Rmd, so it should be just 

```
![Diagram listing the 17 Sustainable Development Goals. Figure from [un.org](https://sdgs.un.org/goals)](sustainabledevgoals.png)
```

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +![The World Bank's Chart. Figure from [worldbank.org](https://datatopics.worldbank.org/sdgatlas/archive/2017/SDG-01-no-poverty.html)](/Users/isabelazeberio/Documents/GitHub/dataviz/_projects/2022/100
Use the relative path.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +world_bank <- read_delim("/Users/isabelazeberio/Documents/GitHub/dataviz/_projects/2022/100386498/povertyline.csv",
Use the relative path.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +![Table 2: International Poverty Lines: Median and mean national lines, by group. Figure from [Jolliffe & Beer Prydz (2016)](https://datatopics.worldbank.org/sdgatlas/archive/2017/SDG-01-no-poverty.h
Use the relative path.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +```{r echo=FALSE, fig.width=15,fig.height=12,fig.align = "center"}
Please do not hide any chunk. Remove the `echo=FALSE`. In fact, you could merge this chunk with the previous one.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +```{r include=FALSE}
Please do not hide any chunk. Remove the `include=FALSE`.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +```{r include=FALSE}
Please do not hide any chunk. Remove the `include=FALSE`.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +```{r include=FALSE}
Please do not hide any chunk. Remove the `include=FALSE`.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +```{r include=FALSE}
Please do not hide any chunk. Remove the `include=FALSE`.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +![Diagram listing the 17 Sustainable Development Goals. Figure from [un.org](https://sdgs.un.org/goals)](/Users/isabelazeberio/Documents/GitHub/dataviz/_projects/2022/100386498/sustainabledevgoals.pn
Please, also, add `{.external width="100%"}` to the end of the line.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +![The World Bank's Chart. Figure from [worldbank.org](https://datatopics.worldbank.org/sdgatlas/archive/2017/SDG-01-no-poverty.html)](/Users/isabelazeberio/Documents/GitHub/dataviz/_projects/2022/100
Please, also, add `{.external width="100%"}` to the end of the line.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +```{r echo=FALSE, fig.width=15,fig.height=12,fig.align = "center"}
Additionally, I think this plot would look nicer with something like `fig.asp="0.3"`  (after removing the current `fig.height`) and `layout="l-page"` or even `layout="l-screen"`. You can play with those values.

2023-01-05 15:27 UTC, Enchufa2 commented on _projects/2022/100386498/100386498.Rmd
> +```{r fig.width=100,fig.height=90,fig.align = "center"}
Currently, this plot doesn't fit into my screen vertically. A `fig.asp=0.7`  (after removing the current `fig.height`) may look better.

2023-01-06 22:04 UTC, isazeberio commented
Hi Iñaki,
I changed the details you mentioned in your review, thank you very much!! The only thing I am not very happy with my work is the dimensions of the graph with the 4 facets. I haven't been able to match layout="l-page" with ggrepel very well.

2023-01-08 17:19 UTC, Enchufa2 commented
Great, but you need to commit and push all the changes! :) Meaning... add the whole `_projects` folder, commit and push it.

2023-01-08 19:06 UTC, Enchufa2 approved these changes
Great job, thanks! I've included a few minor tweaks (the `fig.asp` must be numeric ;-) ) that you can get by clicking **Pull** in RStudio. Merging!

2023-01-08 19:06 UTC, merged

2023-01-08 19:10 UTC, Enchufa2 commented
And here you are: https://csslab.uc3m.es/dataviz/projects/2022/100386498/