Project - <Jia Lin>
IBiDat/dataviz pull request #71
Opened 2024-11-06 16:41 UTC by JacklynLin

First version of the individual project

2024-12-26 20:48 UTC, Enchufa2 requested changes
Nice work! Some comments:

- Please move the files under the `_projects/2024/100536210` directory, i.e. the one starting with the underscore. You should leave `projects` unchanged.
- Please add a caption to the original plot at the beginning, and set it as "external" as e.g. David does [here](https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/2024/100535712/100535712.Rmd#L26).
- When you use `read_delim`, use just `"goal12.cwon.csv"`, not the whole path in your computer. It's not necessary because the file is next to the Rmd.
- There are chunks that would produce a plotly output, but you instead include an image. It would be better to actually execute those chunks and let the document render the plotly result, instead of adding the image manually.

It's a pitty that you don't use ggplot2 at all. It's nice to provide an interactive version, but the course is about ggplot2.

2025-01-04 14:24 UTC, JacklynLin commented
Dear Iñaki,

Happy new year!

Thank you very much for your detailed feedback and constructive suggestions
on my project. I have carefully reviewed each point and would like to
address them as follows:

   1.

   *File Structure*:
   I will move the files under the _projects/2024/100536210 directory as
   suggested, leaving the projects folder unchanged.
   2.

   *Plot Caption*:
   I will add a caption to the original plot at the beginning of the
   document and set it as "external," as recommended.
   3.

   *File Path in read_delim*:
   I will modify the code to use "goal12.cwon.csv" directly instead of the
   full path. This adjustment will make the code cleaner and ensure better
   portability.
   4.

   *Plotly Output and Image*:
   Regarding the chunks that produce a Plotly output, the reason I included
   images instead of directly rendering the plots is due to the use of Shiny
   in this part of the code. Without adding images manually, it was not
   possible to render the plots properly in the R Markdown document. If you
   have suggestions or alternatives to improve this implementation, I would be
   more than happy to explore them and adapt the project accordingly.
   5.

   *Use of ggplot2*:
   I understand your concern about the focus of the course on ggplot2. My
   decision to use Plotly was driven by its efficiency and simplicity for
   creating interactive and dynamic visualizations. I found its logic to be
   somewhat similar to ggplot2, and my ability to implement it was based on
   the concepts I learned in this course.
   That being said, I understand that aligning with the course objectives
   is important. I would like to ask whether not using ggplot2 in this
   specific case might affect the evaluation of my project. If so, I will put
   in the effort to revise the project and incorporate ggplot2
   visualizations, even though my earlier attempts did not yield the ideal
   results.

Thank you again for your guidance and feedback. I will make the necessary
adjustments promptly and update the pull request. Please let me know if
there are any additional points or suggestions I should consider.

Best regards,
Jia Lin

Iñaki Ucar ***@***.***> 于2024年12月26日周四 21:48写道：

> ***@***.**** requested changes on this pull request.
>
> Nice work! Some comments:
>
>    - Please move the files under the _projects/2024/100536210 directory,
>    i.e. the one starting with the underscore. You should leave projects
>    unchanged.
>    - Please add a caption to the original plot at the beginning, and set
>    it as "external" as e.g. David does here
>    <https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/2024/100535712/100535712.Rmd#L26>
>    .
>    - When you use read_delim, use just "goal12.cwon.csv", not the whole
>    path in your computer. It's not necessary because the file is next to the
>    Rmd.
>    - There are chunks that would produce a plotly output, but you instead
>    include an image. It would be better to actually execute those chunks and
>    let the document render the plotly result, instead of adding the image
>    manually.
>
> It's a pitty that you don't use ggplot2 at all. It's nice to provide an
> interactive version, but the course is about ggplot2.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IBiDat/dataviz/pull/71#pullrequestreview-2523479404>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BD3HW2HYT4ADASCSG6LLQH32HRTSNAVCNFSM6AAAAABRJIHNOWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRTGQ3TSNBQGQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2025-01-10 10:28 UTC, Enchufa2 commented
> *Plotly Output and Image*: Regarding the chunks that produce a Plotly output, the reason I included images instead of directly rendering the plots is due to the use of Shiny in this part of the code. Without adding images manually, it was not possible to render the plots properly in the R Markdown document. If you have suggestions or alternatives to improve this implementation, I would be more than happy to explore them and adapt the project accordingly.

- In the chunks where you want to show a table, you could just call e.g. `head(goal_12)` at the end of the chunk to automatically show a few rows of that specific dataframe, instead of including an image.
- In the plotly chunks, ok, I see the issue. You can leave the images.

> 5. *Use of ggplot2*: I understand your concern about the focus of the course on ggplot2. My decision to use Plotly was driven by its efficiency and simplicity for creating interactive and dynamic visualizations. I found its logic to be somewhat similar to ggplot2, and my ability to implement it was based on the concepts I learned in this course. That being said, I understand that aligning with the course objectives is important. I would like to ask whether not using ggplot2 in this specific case might affect the evaluation of my project. If so, I will put in the effort to revise the project and incorporate ggplot2 visualizations, even though my earlier attempts did not yield the ideal results.

Yes, it would be great if you could add a replication in ggplot2 at the beginning, and then switch to plotly as an improvement.

2025-01-13 09:28 UTC, Enchufa2 approved these changes
Looks good, merging!

2025-01-13 09:28 UTC, merged

2025-01-13 09:31 UTC, Enchufa2 commented
And here you are, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100536210/

2025-01-13 17:57 UTC, JacklynLin commented
Thank you very much and have a nice evening!

Iñaki Ucar ***@***.***> 于2025年1月13日周一 10:31写道：

> And here you are, congrats!
> https://csslab.uc3m.es/dataviz/projects/2024/100536210/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IBiDat/dataviz/pull/71#issuecomment-2586602488>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BD3HW2H6RFUK25W7JI73L3D2KOBYTAVCNFSM6AAAAABRJIHNOWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOBWGYYDENBYHA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>