Project - Yijia Lin
IBiDat/dataviz pull request #72
Opened 2024-11-06 19:26 UTC by Yicaa

Initial version of the project

2024-12-23 20:47 UTC, Yicaa commented
Hola, Iñaki, estoy intentando subir la primera versión de mi proyecto, pero no sé si se ha subido correctamente a Github. Te agradezco mucho si me puedes confirmar, gracias;)

2024-12-23 20:52 UTC, Yicaa commented
Por cierto, me parece que la parte interactiva con shiny no se ha rendered bien, no sé cómo se puede conseguirlo, te agradezco mucho si me puedes ayudar, o si es muy complicado, me la quitaré.

2024-12-26 11:47 UTC, Enchufa2 commented
Received! Shiny is not going to work in this blog post. You could publish something in shinyapps.io and then link it here, but I'm more interested in the static part with ggplot2.

2024-12-26 20:59 UTC, Enchufa2 requested changes
Nice work! Some comments:

- It would be nice to explain what "ODA" is in the YAML header's description field.
- See how to add a caption to the original plot at the beginning, and set it as "external" as e.g. David does [here](https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/2024/100535712/100535712.Rmd#L26).
- Please add the option `preview=TRUE` to the chunk that produces the chart that you would like to see as preview in the project gallery.
- As discussed, Shiny is not going to work here, so it's better to avoid it. You could publish something in shinyapps.io and link it here, but I'm primarily interested in the static version with ggplot2.
- There shouldn't be any files outside the `_projects/2024/100452242` directory. Render the Rmd and the html is generated there, you don't need to copy it anywhere else.

2025-01-05 09:13 UTC, Yicaa commented
Hi Iñaki, happy new year and hope you've enjoyed it a lot.
Thank you so much for your feedback, I have followed point by point and hope this 3rd version would be ready to merge;)

2025-01-10 10:46 UTC, Enchufa2 approved these changes
Great work! I made some cleanup, and I forgot to mention... it's better to avoid adding a font with copyright restrictions, so I switched to Noto Sans in Google Fonts. It's not the same, but similar enough. Merging!

2025-01-10 10:47 UTC, merged

2025-01-10 10:53 UTC, Enchufa2 commented
And you are online, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100452242/

2025-01-10 12:59 UTC, Yicaa commented
Thank you so much for your help, Iñaki!