Initial commit
IBiDat/dataviz pull request #74
Opened 2024-11-07 16:48 UTC by pbloas

2025-01-09 17:55 UTC, Enchufa2 requested changes
Neat! Some comments inline.

2025-01-09 17:55 UTC, Enchufa2 commented on _projects/2024/100453237/100453237.Rmd
> +title: "Ternary graph by ‘The Economist’: The world’s most, and least, walkable cities"
Just "The world’s most, and least, walkable cities" is better in my opinion. You could add that it's a ternary graph in the description below.

2025-01-09 17:55 UTC, Enchufa2 commented on _projects/2024/100453237/100453237.Rmd
> +![](images/graph.png){width="538"}
Please add a caption, and set it as "external" as e.g. David does [here](https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/2024/100535712/100535712.Rmd#L26).

2025-01-09 17:55 UTC, Enchufa2 commented on _projects/2024/100453237/100453237.Rmd
> +library(shiny)
Please remove shiny here, because you cannot use it in the post. In general, it is a good practice to remove any library that is not directly called in your code, so that another person trying to replicate this can install only the minimal set of packages required. E.g. are you using magick? (Didn't check).

2025-01-09 17:55 UTC, Enchufa2 commented on _projects/2024/100453237/100453237.Rmd
> +cities <- read_csv2("D:/COMPUTATIONAL SOCIAL SCIENCE/First semester/Data visualization/data/cities.csv")
Data should be part of your PR. Put them close to the Rmd, and these lines should be just `read_csv("ModalShare.csv"`, etc.

2025-01-10 13:49 UTC, Enchufa2 approved these changes
Thanks, merging!

2025-01-10 13:49 UTC, merged

2025-01-10 13:53 UTC, Enchufa2 commented
Neat project, congrats! Here you are: https://csslab.uc3m.es/dataviz/projects/2024/100453237/

2025-01-10 14:49 UTC, pbloas commented
Thank you!