Project - Brad McKenzie
IBiDat/dataviz pull request #75
Opened 2024-11-11 20:55 UTC by bm-go

Initial request to setup dataviz final project

2024-12-21 19:06 UTC, bm-go reviewed
Hi Iñaki, the initial version of my project is ready for review!

2025-01-09 18:20 UTC, Enchufa2 requested changes
Great work! Some comments below.

2025-01-09 18:20 UTC, Enchufa2 commented on _projects/2024/100535241/100535241.Rmd
> +    code_folding: true
Remove these two to keep a uniform style, please.

2025-01-09 18:20 UTC, Enchufa2 commented on _projects/2024/100535241/100535241.Rmd
> +# About the graph
The main title of the post is a level-1 heading. So please your top-level headings should be `##`, then `###` etc. for subsections.

2025-01-09 18:20 UTC, Enchufa2 commented on _projects/2024/100535241/100535241.Rmd
> +knitr::include_graphics("~/Documents/UC3M - coursework/Data Vizualisation/dataviz/ABC_tax_income_plot.png")
This graph should be included in the PR close to this Rmd, and then this should be just `knitr::include_graphics("ABC_tax_income_plot.png")`

2025-01-09 18:20 UTC, Enchufa2 commented on _projects/2024/100535241/100535241.Rmd
> +```{r original-plot, echo=FALSE, fig.cap="Original graph from ABC article", layout="l-body-outset"}
Please add the option `out.extra="class=external"`.

2025-01-09 18:20 UTC, Enchufa2 commented on _projects/2024/100535241/100535241.Rmd
> +
This is fine, but if the resource doesn't exist in the future, your post cannot be replicated. So in the same way as with the original plot above, just include the file in your PR close to this Rmd, and then just `data <- read_excel("ts21individual15occupationsex.xlsx")`.

2025-01-09 18:20 UTC, Enchufa2 commented on _projects/2024/100535241/100535241.Rmd
> +# Basic plotting to check variable functionality.
Please remove full stops at the end of titles.

2025-01-09 18:20 UTC, Enchufa2 commented on _projects/2024/100535241/100535241.Rmd
> +img_grob <- rasterGrob(as.raster(img_transparent), interpolate = TRUE)
Same idea as before: include the image in the PR and avoid paths that belong to your computer. :)

2025-01-09 18:20 UTC, Enchufa2 commented on _projects/2024/100535241/100535241.Rmd
> +```
Fix this path when you include the image in the PR, please.

2025-01-09 18:27 UTC, Enchufa2 commented
Also, please add `preview = TRUE` in the chunk options for the chunk producing the final replication, so that this image is shown in the projects list.

2025-01-14 12:10 UTC, Enchufa2 commented
Just a kind reminder that the deadline is tomorrow. :)

2025-01-14 15:33 UTC, bm-go commented
Hello! All comments should now be addressed. I have committed changes and pushed back for any final checks and changes!

2025-01-15 17:35 UTC, Enchufa2 approved these changes
Nice, thanks! Merging after adding the resulting images too.

2025-01-15 17:35 UTC, merged

2025-01-15 17:45 UTC, Enchufa2 commented
Here's your post, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100535241/

2025-01-15 19:02 UTC, bm-go reviewed
Found an error on the publication with the image final plot image generation, may need to push/pull my own figure-html5 folder?

2025-01-15 19:02 UTC, bm-go commented on _projects/2024/100535241/100535241_files/figure-html5/final-legend-joinplot-1.png
Hi @Enchufa2, seems to have been an error with the image generation. The legend for the final plot .png file is distorted. It's strange because the plot appears fine in my own .Rmd file and the file .../figure-html5/final-legend-joinplot-1.png.

Would this be the fix: I commit and push back my images in the figure-html5 files, then reopen this pull request to fix the images? 

Thanks!

2025-01-15 19:06 UTC, Enchufa2 commented
Ah, let me see if I can fix it.

2025-01-15 19:23 UTC, Enchufa2 commented
[Better now](https://csslab.uc3m.es/dataviz/projects/2024/100535241/#final-replication)? The limits of the inset were... odd. I've also removed the need for saving the legend in the first place.

2025-01-15 23:02 UTC, bm-go commented
Thanks for the removal of the image save, more efficient. 

Your changes look sensible, but it has cut off the last few letters of the legend and changed the sizing a bit. I'm not too worried about the exactness of it. But just to ensure it's all at least readable, can you update these lines of code? I don't think I can do it now that it's published to your main repos. 

**Line 458:**  (to expand legend width to show the full labels)
Current:   lims(x=c(-3,20))+
Update to:  _lims(x=c(-3,21))+_ 

**Lines 489-493:** (slight realignment/sizing)
Current:   inset_element(concentric_plot,
                              left=0.02,
                              bottom=0.96,
                              right=0.32,
                              top=1.005,
Update to:   _inset_element(concentric_plot,
                              left=0.01,
                              bottom=0.955,
                              right=0.4,
                              top=1.01,_

Apologis for the minor adjustments. Hopefully my checks line up and this finalises it!!!

2025-01-16 09:07 UTC, Enchufa2 commented
Ok, done!

2025-01-16 09:20 UTC, bm-go commented
Thank you! Fixed :)