Project - Irene Bosque Gala
IBiDat/dataviz pull request #78
Opened 2024-11-25 11:55 UTC by irenebosque25

Creating a new pull request

2024-12-26 13:13 UTC, irenebosque25 commented
.

2025-01-09 18:38 UTC, Enchufa2 requested changes
Great work! Some comments below.

2025-01-09 18:38 UTC, Enchufa2 commented on _projects/2024/100535296/100535296.Rmd
> +author: "Irene Bosque Gala"
Unfortunately, this template considers the last word as your surname, so it's better to define here "Irene Bosque-Gala".

2025-01-09 18:38 UTC, Enchufa2 commented on _projects/2024/100535296/100535296.Rmd
> +# ORIGINAL GRAPH
Please, set all titles in sentence case.

Also, the main title of the post is a level-1 heading. You should start with `##` for sections, then `###` for subsections and so on.

2025-01-09 18:38 UTC, Enchufa2 commented on _projects/2024/100535296/100535296.Rmd
> +knitr::include_graphics("C:/Users/irene/OneDrive/Escritorio/MUCSS/Data Visualisation/dataviz/432ccc9bae023c97f2f7a035df4d3e13.jpg")
Include this file in the PR close to this Rmd, then call the name of the file, without any path.

Also, set `fig.cap="some caption here"` and `out.extra="class=external"` as chunk options.

2025-01-09 18:38 UTC, Enchufa2 commented on _projects/2024/100535296/100535296.Rmd
> +olympics3 <- read_csv("athlete_events1.csv")
Include this file in the PR, please. Otherwise, I cannot recreate your post! :)

2025-01-09 18:38 UTC, Enchufa2 commented on _projects/2024/100535296/100535296.Rmd
> +font_add(family = "Arial", regular = "C:/Windows/Fonts/arial.ttf")
This should be avoided. These files exist in your computer, but not in e.g. mine. I prefer if you select some font from Google Fonts that is close but not exact rather than this.

2025-01-09 18:38 UTC, Enchufa2 commented on _projects/2024/100535296/100535296.Rmd
> +```{r, fig.width=4, fig.height=6, out.width="100%"}
Please add `preview = TRUE` so that this image is shown in the list of projects.

2025-01-14 12:10 UTC, Enchufa2 commented
Just a kind reminder that the deadline is tomorrow. :)

2025-01-15 17:48 UTC, Enchufa2 commented
Are you still working on this? Some (most) comments were not addressed.

2025-01-15 17:58 UTC, irenebosque25 commented
Hello! I'm so sorry, I think I uploaded the wrong file. I think now should be good. Thank you very much!

2025-01-15 18:56 UTC, Enchufa2 approved these changes
Thanks, nice work! I tried to tweak figure sizes a bit, but not having used `fig.showtext=TRUE` from the beginning turned problematic, and we don't have more time for fine tuning. Merging!

2025-01-15 18:57 UTC, merged

2025-01-15 19:03 UTC, Enchufa2 commented
And here you are, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100535296/