Project - Jorge Ramos
IBiDat/dataviz pull request #81
Opened 2024-12-20 17:17 UTC by jjorgeramos

Good Evening Iñaki, 

I have already uploaded the initial version of the project. 

I look forward to receiving your contribution.

2025-01-09 19:04 UTC, Enchufa2 requested changes
Great work! Some comments below.

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +First I load the libraries that I will need to make the plot:
Please divide your post in sections (e.g. `## Introduction`) and subsections e.g. `### Some subsection`) for readability. See other posts in the gallery.

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +library(devtools)
Is devtools really needed? In general, keep the number of libraries to a minimum. Just those strictly used by you directly.

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +Now, I can start with the data i need to make the graph. In the original plot from El Orden Mundial there is one papers where they extract the information. These are: UNODC (2018): World Drug Report
Check the text for typos, please (e.g. "i need"). RStudio has autocorrect tools. ;-)

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +First I load the libraries that I will need to make the plot:
And first of all, please show the graph you selected and talk a little bit about it. See other published projects for reference.

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +install_local("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/flagon-master")
Ah, I see. No, it's better to avoid this. Just mention that the flagon package is avaiable only on GitHub and link the project in the text.

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +CostaRica <- readPNG(flagon::flags("cr"))
You only need 3 special flags not included in flagon, right? Then remove the rest of them from the "Flags" directory. And those 3 should be just

```r
Inglaterra <- readPNG("Flags/blablabla.png")
```

etc.

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +logo2 <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/cuch.png")
Please include these images (in general, any external files) in the PR close to this Rmd, then call them just by their name, without any path (note that these paths are in YOUR computer).

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +```{r, fig.width= 8.5, fig.height= 6}
This chunk produces the final replication, right? Then please include `preview = TRUE` as a chunk option in order to show this in the project list.

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +logo5 <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/ray.png")
Same as before.

2025-01-09 19:04 UTC, Enchufa2 commented on _projects/2024/100541120/100541120.Rmd
> +library(devtools)
Also, you only need to load the libraries once. Please remove repeated calls below.

2025-01-09 21:19 UTC, jjorgeramos commented
Buenas noches Iñaki,
estaba revisando las cosas que tengo que mejorar pero no acabo de entender
la parte de las imágenes. You only need 3 special flags not included in
flagon, right? Then remove the rest of them from the "Flags" directory. And
those 3 should be just

Inglaterra <- readPNG("Flags/blablabla.png")

o esto Please include these images (in general, any external files) in the
PR close to this Rmd, then call them just by their name, without any path
(note that these paths are in YOUR computer).

¿Tendría que ponerlos en la carpeta del proyecto, cambiar el código y luego
hacer el commit?


Muchas gracias de antemano.

El jue, 9 ene 2025 a las 20:04, Iñaki Ucar ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Great work! Some comments below.
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909297424>:
>
> > @@ -0,0 +1,997 @@
> +---
> +title: "Cocaine consumption"
> +description: |
> +  This project aims to provide insights into the principal consumers of cocaine through a bar plot. I chose this topic because I find it interesting and relevant, especially in relation to the global issues surrounding drug trafficking.
> +  The bar plot serves as an effective tool to visually compare the data, making complex information more accessible and understandable. I was particularly inspired by the work of El Orden Mundial, which I consider they do a great job of visualizing data.
> +categories: "2024"
> +author: Jorge Ramos
> +date: "`r Sys.Date()`"
> +output:
> +  distill::distill_article:
> +    self_contained: false
> +    toc: true
> +---
> +
> +First I load the libraries that I will need to make the plot:
>
> Please divide your post in sections (e.g. ## Introduction) and
> subsections e.g. ### Some subsection) for readability. See other posts in
> the gallery.
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909298152>:
>
> > +library(ggplot2)
> +library(sf)
> +library(ggspatial)
> +library(rnaturalearth)
> +library(rnaturalearthdata)
> +library(tibble)
> +library(ggimage)
> +library(tibble)
> +library(grid)
> +library(png)
> +library(ggtext)
> +library(tidyverse)
> +library(showtext)
> +library(extrafont)
> +library(png)
> +library(devtools)
>
> Is devtools really needed? In general, keep the number of libraries to a
> minimum. Just those strictly used by you directly.
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909299166>:
>
> > +library(rnaturalearthdata)
> +library(tibble)
> +library(ggimage)
> +library(tibble)
> +library(grid)
> +library(png)
> +library(ggtext)
> +library(tidyverse)
> +library(showtext)
> +library(extrafont)
> +library(png)
> +library(devtools)
> +library(flagon)
> +```
> +
> +Now, I can start with the data i need to make the graph. In the original plot from El Orden Mundial there is one papers where they extract the information. These are: UNODC (2018): World Drug Report 2018: opioid crisis, prescription drug abuse expands; cocaine and opium hit record highs.
>
> Check the text for typos, please (e.g. "i need"). RStudio has autocorrect
> tools. ;-)
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909303501>:
>
> > +#Install the package:
> +library(devtools)
> +install_local("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/flagon-master")
>
> Ah, I see. No, it's better to avoid this. Just mention that the flagon
> package is avaiable only on GitHub and link the project in the text.
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909305684>:
>
> > +Australia <- readPNG(flagon::flags("au"))
> +Albania <- readPNG(flagon::flags("al"))
> +Estados_Unidos <- readPNG(flagon::flags("us"))
> +Escocia <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/flagon-master/inst/png/sct.png")
> +Inglaterra <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/Images/England and Wales.png")
> +España <-  readPNG(flagon::flags("es"))
> +Paises_Bajos <- readPNG(flagon::flags("nl"))
> +Irlanda_norte <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/Images/Northern Ireland.png")
> +Uruguay <- readPNG(flagon::flags("uy"))
> +Argentina <- readPNG(flagon::flags("ar"))
> +Irlanda <- readPNG(flagon::flags("ie"))
> +Canada <- readPNG(flagon::flags("ca"))
> +Polonia <- readPNG(flagon::flags("pl"))
> +Chile <- readPNG(flagon::flags("cl"))
> +CostaRica <- readPNG(flagon::flags("cr"))
>
> You only need 3 special flags not included in flagon, right? Then remove
> the rest of them from the "Flags" directory. And those 3 should be just
>
> Inglaterra <- readPNG("Flags/blablabla.png")
>
> etc.
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909306588>:
>
> > +logo1 <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/eom.png")
> +logo2 <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/cuch.png")
>
> Please include these images (in general, any external files) in the PR
> close to this Rmd, then call them just by their name, without any path
> (note that these paths are in YOUR computer).
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909307329>:
>
> > +  annotation_raster(Australia, xmin = 14.6, xmax = 15.3, ymin = -0.62, ymax = -0.34)
> +
> +
> +#Now, we can display the final plot with flags
> +flag_plot
> +
> +```
> +
> +
> +As we can see, one problem I encountered was with the quality of the flags in the graph. Despite using the annotation_raster() function to add them, the quality of the flags appeared quite poor.
> +For the shades that has the authentic graph, I tried to introduce grey rectangles on the back of the flags but it wasn't a good option. Also I tried to edit the images of the packages but then when I tried to introduce those flags in the graph they dissappeared.
> +
> +
> +The next step is to introduce the logos. These original figures were difficult to find, so I decided to made a screenshot of the original plot and introduce the pictures with patchwork package.
> +
> +```{r, fig.width= 8.5, fig.height= 6}
>
> This chunk produces the final replication, right? Then please include preview
> = TRUE as a chunk option in order to show this in the project list.
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909307848>:
>
> > +logo3 <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/tur.png")
> +logo3_grob <- rasterGrob(logo3, interpolate = TRUE)
> +logo4 <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/tur1.png")
> +logo4_grob <- rasterGrob(logo4, interpolate = TRUE)
> +logo5 <- readPNG("C:/Users/jorge/Desktop/CSS/Data-Visualization/Cocaine in Europe - Datavis/ray.png")
>
> Same as before.
> ------------------------------
>
> In _projects/2024/100541120/100541120.Rmd
> <https://github.com/IBiDat/dataviz/pull/81#discussion_r1909301703>:
>
> > @@ -0,0 +1,997 @@
> +---
> +title: "Cocaine consumption"
> +description: |
> +  This project aims to provide insights into the principal consumers of cocaine through a bar plot. I chose this topic because I find it interesting and relevant, especially in relation to the global issues surrounding drug trafficking.
> +  The bar plot serves as an effective tool to visually compare the data, making complex information  [...]

2025-01-10 11:01 UTC, Enchufa2 commented
> Buenas noches Iñaki, estaba revisando las cosas que tengo que mejorar pero no acabo de entender la parte de las imágenes. You only need 3 special flags not included in flagon, right? Then remove the rest of them from the "Flags" directory. And those 3 should be just Inglaterra <- readPNG("Flags/blablabla.png")

Quería decir que has incluido imágenes de banderas en el PR, pero por otra parte cargas la mayoría de las banderas desde flagon. Entonces elimina las banderas que no se necesitan del PR. Por otro lado, las especiales no están aquí en PNG, solo veo SVG.

> o esto Please include these images (in general, any external files) in the PR close to this Rmd, then call them just by their name, without any path (note that these paths are in YOUR computer). ¿Tendría que ponerlos en la carpeta del proyecto, cambiar el código y luego hacer el commit?

Sí. Esto tiene que ser replicable. Si hay rutas de tu ordenador a archivos que no están incluidos aquí, no puedo darle a knitr y replicar tu post. Todo lo que uses externo (imágenes, datos...) tiene que estar incluido en el pull request en la misma carpeta que el Rmd. Y referirte a ellos simplemente por el nombre del archivo, porque ya están junto al Rmd, no hace falta que incluyas la ruta completa al archivo.

2025-01-14 12:10 UTC, Enchufa2 commented
Just a kind reminder that the deadline is tomorrow. :)

2025-01-14 12:11 UTC, jjorgeramos commented
Hola Iñaki perdona pero he estado muy agobiado. Solo me faltan unos
detalles, esta noche lo hago.

El El mar, 14 ene 2025 a las 13:10, Iñaki Ucar ***@***.***>
escribió:

> Just a kind reminder that the deadline is tomorrow. :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IBiDat/dataviz/pull/81#issuecomment-2589751001>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMFJBZYD6VZWIN6BLRY5VML2KT5E3AVCNFSM6AAAAABT7QUSVCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOBZG42TCMBQGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-15 18:29 UTC, Enchufa2 commented
I assume this is not ready because in the last commit I only see some new flags. Let me know with a comment here when it's ready, please.

2025-01-15 18:47 UTC, jjorgeramos commented
Hi Iñaki, 
I am having problems. I have selected all my files but I don't know why there are not showing here.

2025-01-15 19:04 UTC, Enchufa2 commented
Please don't close the PR. Are these your latest changes? https://github.com/IBiDat/dataviz/pull/81/commits/e7c53f37341e95440135521a8ce44d4abc150824

2025-01-15 19:12 UTC, jjorgeramos commented
I am experiencing issues with commits on GitHub, and I accidentally closed a pull request I was working on. I believe I have followed all the necessary steps as per the instructions, but I cannot identify the errors that might be causing the problem. My intention was to reopen the pull request after closing it, but I made a mistake in doing so. Since the deadline is approaching, I will not make any further modifications to the project.

2025-01-15 19:24 UTC, Enchufa2 commented
But was the commit I referenced above correct? It says "Last attempt :)"

2025-01-15 19:27 UTC, jjorgeramos commented
Yes, it is. 
Sorry for the confusion.

2025-01-16 10:54 UTC, Enchufa2 approved these changes
Thanks, merging after some heavy cleanup... :-P

2025-01-16 10:54 UTC, merged

2025-01-16 11:02 UTC, Enchufa2 commented
Here's your work, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100541120/