Initial version of the project.
IBiDat/dataviz pull request #82
Opened 2024-12-22 12:03 UTC by marvinstruckmeyer

2025-01-09 19:12 UTC, Enchufa2 requested changes
Very neat, great work! Just minor comments.

2025-01-09 19:12 UTC, Enchufa2 commented on _projects/2024/100540594/100540594.Rmd
> +![Original visualization from resourcetrade.earth](Original_plot.png){.external width="100%"}
This file is missing, please add it. :)

2025-01-09 19:12 UTC, Enchufa2 commented on _projects/2024/100540594/100540594.Rmd
> +  sheet = "Trades")
Just the name of the file, without `here("projects", "2024", ...)` please.

2025-01-09 19:12 UTC, Enchufa2 commented on _projects/2024/100540594/100540594.Rmd
> +      png::readPNG(here("_projects", "2024", "100540594", "legend.png")),
Same, just the name of the file, without `here("projects", "2024", ...)` please.

2025-01-10 12:26 UTC, marvinstruckmeyer commented
Hi Iñaki, thanks for your comments. I hope I could fix the three suggestions. Let me know if there's anything else.

2025-01-10 14:01 UTC, Enchufa2 approved these changes
Neat, thanks! I just had to change `get.edge` with `ends`, because it seems that the former is defunct and replace with this new one in newer versions of igraph. Merging!

2025-01-10 14:01 UTC, merged

2025-01-10 14:06 UTC, Enchufa2 commented
Here you are, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100540594/

2025-01-10 15:29 UTC, marvinstruckmeyer commented
Thank you, Iñaki!