REPLICA AND IMPROVEMENT MAP WHERE DO 8 BILLION PEOPLE LIVE
IBiDat/dataviz pull request #83
Opened 2024-12-23 10:18 UTC by albavega22

El mapa original es el de Where do 8 billion people live, aquí subo los archivos rmd y html, así como las bases de datos usadas.

2024-12-23 10:22 UTC, Enchufa2 commented
Ah, didn't see this one, perfect. Don't close it!

2024-12-23 10:23 UTC, albavega22 commented
Ah, genial, ¿entonces ya está bien o tengo que cambiar algo más?

2025-01-09 19:50 UTC, Enchufa2 requested changes
Great work! A couple of comments:

- I see two Rmds. The one that I expect, with your NIA as name, and another that is outside of your folder that is called "REPLICA AND IMPROVEMENT_ALBA GARCIA VEGA.Rmd". Please remove this last one (and incorporate any thing you did there that it's not in the other, just in case).
- The programming work is done, but I expect a post, not just the code. ;-) Please see the projects that are already published online for reference.

2025-01-14 12:10 UTC, Enchufa2 commented
Just a kind reminder that the deadline is tomorrow. :)

2025-01-14 13:09 UTC, albavega22 commented
Yes, I am working on the final post now!

2025-01-14 14:28 UTC, albavega22 commented
Hi, I am having problems now. How do I create the post? I am confused

2025-01-15 19:43 UTC, Enchufa2 approved these changes
Nice, thanks! Merging after some cleanup and minor changes.

2025-01-15 19:43 UTC, merged

2025-01-15 19:46 UTC, Enchufa2 commented
Here's your work, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100432719/