Project - Mencía Gómez
IBiDat/dataviz pull request #84
Opened 2024-12-23 11:08 UTC by menciagl

First version of the project (plot on migrations).
Added: Check that the year folder has been created correctly (2024) and inside there's the folder with my NIA (100431421)

2025-01-09 20:04 UTC, Enchufa2 requested changes
Great work! Some minor comments below.

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +author: Mencía Gómez Luna
Mencía Gómez-Luna, or the template will recongnize "Luna" as your surname.

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +date: 2024-12-21
Should be ``date: "`r Sys.Date()`"``

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +# WHY DID I CHOOSE THIS PLOT
- All titles in sentence case, please.
- Use `##` for sections instead, and `###` and so on for subsections, please.

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +>
Remove the `>` line before each element of the list, please.

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +I wanted to replicate and improve the EOM plot (https://elordenmundial.com/mapas-y-graficos/inmigrantes-en-el-mundo/) for several reasons. First of all, I chose it since I had never recreated a map b
Include the original plot, with a caption and as "external" as e.g. David does [here](https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/2024/100535712/100535712.Rmd#L26).

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +mapa_mundial <- st_as_sf(getMap(resolution = "low")) #The resolution is low because we don't need very millimetrically details as in other types of more specific maps.
Put this comment in its own line so that it doesn't go out of view.

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +#| fig.asp: 0.7 # to adjust how the plot appears
Add `preview: true` as a chunk option too so that this image is shown in the  project list.

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +    draw_text("% of immigrants and flows of migration (2017)", size = 18, x = 0.08, y = 0.01, hjust = 0, fontface = "bold", color = "#444444"),
This line goes out of view, insert a new line somewhere in the middle to avoid this.

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +Here I tried to apply Iñaki's advice to improve the plot, specifically I take into account these suggestion:
There's no need to mention me all the time: :D

2025-01-09 20:04 UTC, Enchufa2 commented on _projects/2024/100431421/100431421.Rmd
> +First, I think it's better -as you said- that the blue and dark colors are related to lower values and the higher values are represented with more lighter and yellowish colors. But what do you think
And please try to avoid things like "as you said", because this post is not for me, it's also for you, it's for everyone! So imagine some random person arrives to your project and reads this... :)

2025-01-14 12:10 UTC, Enchufa2 commented
Just a kind reminder that the deadline is tomorrow. :)

2025-01-15 14:07 UTC, menciagl commented
Final version: I have added justifications to the reason for the improvements, and the reason for the choice of the scale of the "% migration" variable and the colors

2025-01-15 20:11 UTC, Enchufa2 approved these changes
Nice, thanks! Merging after some cleanup and minor fixes.

2025-01-15 20:11 UTC, merged

2025-01-15 20:15 UTC, Enchufa2 commented
And your work is online, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100431421/