Project – Isabel Monge
IBiDat/dataviz pull request #90
Opened 2024-12-28 00:35 UTC by isabelmonge

This is my first draft! My main issues are embedding the Shiny app directly and fixing long code (titles, captions) that runs off the page. I tried one wrapping solution without success, and another using fvextra, but it's not available for my R version. I’d appreciate any advice on these issues and welcome any other feedback you may have.

https://stackoverflow.com/questions/26210656/in-r-markdown-in-rstudio-how-can-i-prevent-the-source-code-from-running-off-a-p

2025-01-09 20:34 UTC, Enchufa2 requested changes
Great work! Some minor comments below.

2025-01-09 20:34 UTC, Enchufa2 commented on _projects/2024/100542532/100542532.Rmd
> +```{r, echo=FALSE, out.width='100%'}
Please add the options `out.extra="class=external"` and `fig.cap="some text here to show as the caption of the image"`.

2025-01-09 20:34 UTC, Enchufa2 commented on _projects/2024/100542532/100542532.Rmd
> +### **Data**
No need to set it as bold. Please any additional formatting like this from all the titles, so that the style is uniform with respect to other posts in the web.

2025-01-09 20:34 UTC, Enchufa2 commented on _projects/2024/100542532/100542532.Rmd
> +```
Mmmh, note that I cannot run your post in this way. Please remove the load() instruction, it should work just by reading the CSV, right?

2025-01-09 20:34 UTC, Enchufa2 commented on _projects/2024/100542532/100542532.Rmd
> +```{r, out.width='100%'}
Please add `preview = TRUE`, so that this image is shown in the list of projects.

2025-01-09 20:39 UTC, Enchufa2 commented
About your issues:

> This is my first draft! My main issues are embedding the Shiny app directly

As discussed with other classmates during the presentations, this is not possible. The only possibility would be to publish e.g. a dashboard in shinyapps.io, then link it here. But I'm mainly interested in the static part, don't waste so much time in that.

> and fixing long code (titles, captions) that runs off the page. I tried one wrapping solution without success, and another using fvextra, but it's not available for my R version. I’d appreciate any advice on these issues and welcome any other feedback you may have.

The only solution for text that runs off the page is to break it in chunks and paste them together. For example, instead of

```r
text <- "suppose that this is a very large piece of text"
```

you can do

```r
text <- paste(c(
  "suppose",
  "that this",
  "is a very",
  "large piece",
  "of text"
  ), collapse=" ")
```

etc.

2025-01-14 12:10 UTC, Enchufa2 commented
Just a kind reminder that the deadline is tomorrow. :)

2025-01-14 19:48 UTC, isabelmonge commented
The first pull request didn’t work as expected, but the second one should be correct. Please let me know, thank you!

2025-01-16 11:37 UTC, Enchufa2 approved these changes
Thanks, merging after some adjustments and cleanup!

2025-01-16 11:37 UTC, merged

2025-01-16 11:42 UTC, Enchufa2 commented
Here you are, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100542532/