Project - Aurora Sterpellone
IBiDat/dataviz pull request #91
Opened 2024-12-29 10:32 UTC by aurora-ster

Hello Iñaki!
This is the initial version of my project, hope everything works.

Happy holidays!

2025-01-09 20:45 UTC, Enchufa2 requested changes
Great work! Some comments below.

2025-01-09 20:45 UTC, Enchufa2 commented on _projects/2024/100446517/100446517.Rmd
> +  A short description of the post.
So... :)

2025-01-09 20:45 UTC, Enchufa2 commented on _projects/2024/100446517/100446517.Rmd
> +Learn more about using Distill at <https://rstudio.github.io/distill>.
Remove this please

2025-01-09 20:45 UTC, Enchufa2 commented on _projects/2024/100446517/100446517.Rmd
> +# EU Book Reading Habits Graph Replication
Remove this please, the post already has a title ;-)

2025-01-09 20:45 UTC, Enchufa2 commented on _projects/2024/100446517/100446517.Rmd
> +![](images/books-day-MS-2022.png)
Please add a caption, and set it as "external" as e.g. David does [here](https://github.com/IBiDat/dataviz/blob/81084e40371bd8161998806e9c7471e04ad47cfe/_projects/2024/100535712/100535712.Rmd#L26).

Also, the "images" directory is missing. Could you please add it to the PR?

2025-01-09 20:45 UTC, Enchufa2 commented on _projects/2024/100446517/100446517.Rmd
> +data <- read.csv(file = "ilc_scp27_linear.csv")
Add the data too!

2025-01-09 20:45 UTC, Enchufa2 commented on _projects/2024/100446517/100446517.Rmd
> +### **Step 1: Filter Relevant Data**
Please remove any additional formatting like this from all the titles to ensure a uniform style with other articles. I'm referring to the bold text.

2025-01-09 20:45 UTC, Enchufa2 commented on _projects/2024/100446517/100446517.Rmd
> +```
?

2025-01-09 20:45 UTC, Enchufa2 commented on _projects/2024/100446517/100446517.Rmd
> +```{r}
Please add the option `preview=TRUE` so that this image is shown in the gallery.

2025-01-12 08:57 UTC, aurora-ster commented
Hello Iñaki! I have checked your comments and corrected some things. I hope it's better now :)

2025-01-13 15:46 UTC, Enchufa2 commented
Thanks, then [commit and push](https://csslab.uc3m.es/dataviz/tutorials/project/#adding-changes-to-the-article) your changes, please!

2025-01-13 17:40 UTC, aurora-ster commented
I'm so sorry, I was sure I pushed the changes. Hope everything's right now,
thank you!

El lun, 13 ene 2025 a las 16:46, Iñaki Ucar ***@***.***>)
escribió:

> Thanks, then commit and push
> <https://csslab.uc3m.es/dataviz/tutorials/project/#adding-changes-to-the-article>
> your changes, please!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IBiDat/dataviz/pull/91#issuecomment-2587483621>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMFI3W35UZPSKM6WNFF7Q2D2KPNWBAVCNFSM6AAAAABUKVRV5WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOBXGQ4DGNRSGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-13 18:55 UTC, Enchufa2 approved these changes
Perfect, merging!

2025-01-13 18:55 UTC, merged

2025-01-13 18:59 UTC, Enchufa2 commented
And here's your project, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100446517/

2025-01-13 21:11 UTC, aurora-ster commented
Awesome, good news!!  Thank you so much :)

El lun, 13 ene 2025 a las 19:59, Iñaki Ucar ***@***.***>)
escribió:

> And here's your project, congrats!
> https://csslab.uc3m.es/dataviz/projects/2024/100446517/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IBiDat/dataviz/pull/91#issuecomment-2587955462>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMFI3WY4N7UCOI7TF4OQPX32KQEIZAVCNFSM6AAAAABUKVRV5WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOBXHE2TKNBWGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>