Project - Maria Carda
IBiDat/dataviz pull request #92
Opened 2024-12-30 17:22 UTC by mariacardag

Visualization of the housing crisis in Spain according to official data from the Ministry of Transportation

2025-01-10 09:15 UTC, Enchufa2 requested changes
Great work! Some minor comments below.

2025-01-10 09:15 UTC, Enchufa2 commented on _projects/2024/100419840/100419840.Rmd
> +author: Maria Carda Gargallo
Carda-Gargallo. Otherwise, the template would think that only Gargallo is your surname.

2025-01-10 09:15 UTC, Enchufa2 commented on _projects/2024/100419840/100419840.Rmd
> +![Original graph](https://raw.githubusercontent.com/mariacardag/datavizclass/main/image.png)
Please set it as external as e.g. David does [here](https://github.com/IBiDat/dataviz/blob/9a3bc0367b1c0b297765b59ff6f3c34cef06a204/_projects/2024/100535712/100535712.Rmd#L26).

2025-01-10 09:15 UTC, Enchufa2 commented on _projects/2024/100419840/100419840.Rmd
> +mi_grafico_mal <- mi_grafico_mal + geom_step(data = subset(data_filtered, CCAA %in% comunidades_destacadas), aes(color = CCAA),
Note that this line is too wide, and goes off the page in the resulting HTML depending on the screen size. It's a good practice to wrap your code so that every line has a maximum length of 80 characters approx. Review the rest of the post to solve these kind of problems, please.

2025-01-10 09:15 UTC, Enchufa2 commented on _projects/2024/100419840/100419840.Rmd
> +```{r, fig.height=8, fig.width=17}
Please add the option `preview = TRUE` so that this image is highlighted in the gallery.

2025-01-14 12:11 UTC, Enchufa2 commented
Just a kind reminder that the deadline is tomorrow. :)

2025-01-14 16:59 UTC, mariacardag commented on _projects/2024/100419840/100419840.Rmd
> +![Original graph](https://raw.githubusercontent.com/mariacardag/datavizclass/main/image.png)
Hola Iñaki, estoy revisando los cambios, pero tengo un pequeño problema con el link y es que mi gráfico no es una imagen como tal, está hecho con datawrapper, no sé si prefieres que simplemente ponga el link al artículo o si hay alguna manera de importarlo con este - a lo mejor con este link (https://datawrapper.dwcdn.net/YvIFi/2/).  Gracias de antemano :)

2025-01-16 11:57 UTC, Enchufa2 approved these changes
Thanks, merging after some adjustments!

2025-01-16 11:57 UTC, merged

2025-01-16 12:01 UTC, Enchufa2 commented
Here you are, congrats! https://csslab.uc3m.es/dataviz/projects/2024/100419840/